server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: "${APP_NAME:microservice-jwt}"

management:
  health:
    probes:
      enabled: true
  endpoint:
    health:
      show-details: ${SHOW_DETAILS:never}
      enabled: true
      cache:
        time-to-live: "10s"
  endpoints:
    web:
      base-path: "${PATH_BASE:/api/v1/microservice-jwt/}"
      path-mapping:
        health: "health"
        liveness: "liveness"
        readiness: "readiness"
      exposure:
        include: "health, liveness, readiness, metrics"

logging:
  level:
    root: ${LOG4J_LEVEL:INFO}

entries:
  web:
    path-base: "${PATH_BASE:/api/v1/microservice-jwt}"
    path-public: "${PATH_PUBLIC:/public}"
    path-private: "${PATH_PRIVATE:/private}"
    path-user: "${PATH_USER:/user}"
    path-info: "${PATH_INFO:/info}"
    validate-security: "${PATH_VALIDATE_SECURITY:/validate}"
    token: "${PATH_TOKEN_SECURITY:/token}"